# Generated by Django 3.2.9 on 2022-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0036_add_attachment_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='target',
            field=models.CharField(default='axis', help_text='Date this ticket was first created', max_length=50),
            preserve_default=False,
        ),
    ]
