# Generated by Django 3.2.9 on 2022-01-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0037_ticket_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='target',
            field=models.CharField(help_text='Target organistation for this ticket', max_length=50),
        ),
    ]
