# Generated by Django 3.2.9 on 2022-01-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_alter_ticket_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localuser',
            name='organisation',
        ),
        migrations.AddField(
            model_name='localuser',
            name='organisation',
            field=models.ForeignKey(default=1, help_text='Name of the organisation that the user belongs to', on_delete=django.db.models.deletion.CASCADE, to='helpdesk.organisation'),
            preserve_default=False,
        ),
    ]
