# Generated by Django 3.2.9 on 2022-01-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0041_alter_localuser_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.organisation', verbose_name='Target'),
        ),
    ]
