# Generated by Django 3.2.9 on 2022-01-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0042_alter_ticket_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.organisation', verbose_name='Organisation'),
        ),
    ]
