# Generated by Django 3.2.9 on 2022-01-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0043_alter_ticket_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Role', max_length=50)),
                ('organisation', models.ForeignKey(blank=True, help_text='Name of the organisation that the role belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='localuser',
            name='role',
            field=models.ManyToManyField(blank=True, help_text='Roles of the user', null=True, to='helpdesk.Role'),
        ),
    ]
