# Generated by Django 3.2.9 on 2022-02-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0045_alter_ticket_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.role', verbose_name='Target'),
        ),
    ]
